In [1]:
import torch
import lovely_tensors

lovely_tensors.monkey_patch()

In [2]:
from torchrl.objectives.value.utils import _get_num_per_traj, _get_num_per_traj_init

/Users/davidkorcak/.venv/lib/python3.12/site-packages/torchrl/__init__.py:43: UserWarning: failed to set start method to spawn, and current start method for mp is fork.
  warn(


In [13]:
def do_computation(mask):
    return _get_num_per_traj_init(mask)


mask = torch.zeros(2, 6).bool()
mask[:, 0] = True
mask[:, -3] = True
print(mask.p)

outputs = torch.vmap(do_computation, (0,))(mask)
outputs

tensor([[ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False]])


RuntimeError: vmap: We do not support batching operators that can support dynamic shape. Attempting to batch over indexing with a boolean mask.

In [ ]:
_get_num_per_traj_init(mask).p

tensor([3, 3, 3, 3])

In [18]:
def _get_num_per_traj__init_vmap(mask):
    done = torch.zeros_like(mask)
    done[..., :-1] += mask[..., 1:]
    return _get_num_per_traj_vmap(mask)


def _get_num_per_traj_vmap(mask):
    done = mask.clone()
    done[..., -1] = True
    cumsums = torch.cumsum(done, dim=-1)
    print(cumsums.p)

In [ ]:
_get_num_per_traj(mask).p

tensor([1, 3, 2, 1, 3, 2])

In [22]:
mask.p

tensor([[ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False]])

In [21]:
mask.reshape(-1).p

tensor([ True, False, False,  True, False, False,  True, False, False,  True,
        False, False])

In [15]:
mask.cumsum(-1).p

tensor([[1, 1, 1, 2, 2, 2],
        [1, 1, 1, 2, 2, 2]])

In [20]:
_get_num_per_traj__init_vmap(mask)

tensor([[1, 1, 1, 2, 2, 3],
        [1, 1, 1, 2, 2, 3]])


In [16]:
_get_num_per_traj_init(mask).p

tensor([3, 3, 3, 3])