In [1]:
import torch
import lovely_tensors

lovely_tensors.monkey_patch()

In [26]:
from torchrl.objectives.value.utils import _get_num_per_traj, _get_num_per_traj_init

In [32]:
def do_computation(mask):
    dome = mask.expand(mask.sum(), -1)
    return done


mask = torch.zeros(2, 6).bool()
mask[:, 0] = True
mask[:, -3] = True
print(mask.p)

outputs = torch.vmap(do_computation, (0,))(mask)
outputs

tensor([[ True, False, False,  True, False, False],
        [ True, False, False,  True, False, False]])


RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.

In [29]:
_get_num_per_traj_init(mask).p

tensor([3, 3, 3, 3])

In [ ]:
def _get_num_per_traj__init_vmap(mask):
    done = torch.zeros_like(mask)
    done[..., :-1] += mask[..., 1:]
    return _get_num_per_traj_vmap(mask)


def _get_num_per_traj_vmap(mask):
    done = mask.clone()
    done[..., -1] = True

In [30]:
_get_num_per_traj(mask).p

tensor([1, 3, 2, 1, 3, 2])

In [22]:
mask.reshape(-1).p

tensor([False, False,  True, False, False,  True, False, False,  True, False,
        False,  True])

In [23]:
(torch.where(mask.reshape(-1))[0] + 1).p

tensor([ 3,  6,  9, 12])