In [36]:
import torch
import random

x = torch.rand((2, 1), requires_grad=True)
x.retain_grad()

In [37]:
xs = []
for _ in range(10):
    xprime = x + torch.randn_like(x) * x
    xprime.retain_grad()
    xs.append(xprime)
    if random.random() < 0.5:
        mask = x > xprime
        print(mask)
        xprime[mask] = 0.0
    x = xprime

tensor([[ True],
        [False]])
tensor([[False],
        [False]])
tensor([[False],
        [ True]])


In [38]:
x.sum().backward(retain_graph=True)